# src/latest_ai_development/config/tasks.yaml
research_task:
  description: >
    Faça uma pesquisa completa sobre o tópico: {topic}
    Certifique-se de encontrar qualquer informação interessante e relevante sobre pontos turísticos.
  expected_output: >
    Uma lista com 10 tópicos das informações mais relevantes sobre o tópico: {topic}
  agent: researcher

reporting_task:
  description: >
    Revise o contexto que você obteve e expanda cada tópico em uma seção completa para um relatório.
    Certifique-se de que o relatório seja detalhado e contenha toda e qualquer informação relevante.
  expected_output: >
    Um relatório completo com os tópicos principais, cada um com uma seção completa de informações.
    Formatado como markdown sem '```'
  agent: reporting_analyst
  output_file: report.md